# Generated by Django 5.1.7 on 2026-02-25

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppSetting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(max_length=128, unique=True)),
                ("value_json", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ("key",)},
        ),
        migrations.CreateModel(
            name="JobRun",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "job_name",
                    models.CharField(
                        choices=[
                            ("generate-data", "generate-data"),
                            ("load-nosql", "load-nosql"),
                            ("run-producer", "run-producer"),
                            ("mart-refresh", "mart-refresh"),
                            ("run-etl", "run-etl"),
                            ("trigger-airflow-dag", "trigger-airflow-dag"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "queued"),
                            ("running", "running"),
                            ("success", "success"),
                            ("failed", "failed"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("requested_by", models.CharField(blank=True, max_length=150, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.BigIntegerField(blank=True, null=True)),
                ("params_json", models.JSONField(blank=True, default=dict)),
                ("log_path", models.CharField(blank=True, max_length=512, null=True)),
                ("stdout_tail", models.TextField(blank=True, null=True)),
                ("stderr_tail", models.TextField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(fields=["job_name", "created_at"], name="api_jobrun_job_nam_ea9c6b_idx"),
                    models.Index(fields=["status", "created_at"], name="api_jobrun_status_1b1636_idx"),
                ],
            },
        ),
    ]
