# Generated by Django 5.1.7 on 2026-03-06

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PipelinePreset",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=128, unique=True)),
                (
                    "job_name",
                    models.CharField(
                        choices=[
                            ("generate-data", "generate-data"),
                            ("load-nosql", "load-nosql"),
                            ("run-producer", "run-producer"),
                            ("mart-refresh", "mart-refresh"),
                            ("run-etl", "run-etl"),
                            ("trigger-airflow-dag", "trigger-airflow-dag"),
                        ],
                        max_length=64,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("params_json", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_by", models.CharField(blank=True, max_length=150, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ("name",),
                "indexes": [
                    models.Index(fields=["job_name", "is_active"], name="api_pipelin_job_nam_e83350_idx"),
                    models.Index(fields=["updated_at"], name="api_pipelin_updated_9fe030_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ExportAudit",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("storage_provider", models.CharField(default="s3", max_length=32)),
                ("bucket", models.CharField(max_length=255)),
                ("object_key", models.CharField(max_length=512)),
                ("filename", models.CharField(max_length=255)),
                ("rows_count", models.BigIntegerField(blank=True, null=True)),
                ("size_bytes", models.BigIntegerField(default=0)),
                ("etag", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("uploaded", "uploaded"), ("failed", "failed")],
                        default="uploaded",
                        max_length=16,
                    ),
                ),
                ("exported_at", models.DateTimeField(auto_now_add=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "job_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="export_audits",
                        to="api.jobrun",
                    ),
                ),
            ],
            options={
                "ordering": ("-exported_at",),
                "indexes": [
                    models.Index(fields=["status", "exported_at"], name="api_exporta_status_93803f_idx"),
                    models.Index(fields=["bucket", "object_key"], name="api_exporta_bucket_35be90_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AlertEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source", models.CharField(default="grafana", max_length=64)),
                ("channel", models.CharField(default="telegram", max_length=32)),
                ("rule_name", models.CharField(blank=True, max_length=128, null=True)),
                ("entity", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "severity",
                    models.CharField(
                        choices=[("info", "info"), ("warning", "warning"), ("critical", "critical")],
                        default="warning",
                        max_length=16,
                    ),
                ),
                ("observed_value", models.FloatField(blank=True, null=True)),
                ("threshold_value", models.FloatField(blank=True, null=True)),
                ("message", models.TextField()),
                ("payload_json", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[("sent", "sent"), ("failed", "failed")],
                        default="sent",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "job_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alert_events",
                        to="api.jobrun",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(fields=["status", "created_at"], name="api_alertev_status_13fbee_idx"),
                    models.Index(fields=["source", "channel", "created_at"], name="api_alertev_source_52d5ca_idx"),
                ],
            },
        ),
    ]

