# Generated by Django 5.1.7 on 2026-03-14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_service_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("stores", "stores"),
                            ("products", "products"),
                            ("customers", "customers"),
                            ("purchases", "purchases"),
                        ],
                        max_length=32,
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("file_format", models.CharField(blank=True, max_length=16)),
                ("file_path", models.CharField(max_length=512)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "queued"),
                            ("running", "running"),
                            ("success", "success"),
                            ("failed", "failed"),
                            ("partial", "partial"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("requested_by", models.CharField(blank=True, max_length=150, null=True)),
                ("total_rows", models.BigIntegerField(default=0)),
                ("valid_rows", models.BigIntegerField(default=0)),
                ("invalid_rows", models.BigIntegerField(default=0)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(fields=["status", "created_at"], name="api_importba_status_7ae4f8_idx"),
                    models.Index(fields=["entity_type", "created_at"], name="api_importba_entity__f7fe1b_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ImportRowError",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("row_number", models.PositiveIntegerField(default=0)),
                ("field_name", models.CharField(blank=True, max_length=128)),
                ("error_code", models.CharField(max_length=64)),
                ("message", models.TextField()),
                ("raw_fragment", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="row_errors",
                        to="api.importbatch",
                    ),
                ),
            ],
            options={
                "ordering": ("row_number", "id"),
                "indexes": [
                    models.Index(fields=["batch", "row_number"], name="api_importro_batch_i_6b68df_idx"),
                ],
            },
        ),
    ]
