# Generated by Django 5.1.7 on 2026-03-15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_import_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="importbatch",
            name="last_replayed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="replay_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="staged_rows",
            field=models.BigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="ImportStagingRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("stores", "stores"),
                            ("products", "products"),
                            ("customers", "customers"),
                            ("purchases", "purchases"),
                        ],
                        max_length=32,
                    ),
                ),
                ("row_number", models.PositiveIntegerField(default=0)),
                ("business_key", models.CharField(max_length=255)),
                ("payload_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staging_records",
                        to="api.importbatch",
                    ),
                ),
            ],
            options={
                "ordering": ("row_number", "id"),
                "indexes": [
                    models.Index(fields=["batch", "row_number"], name="api_impstg_batch_idx"),
                    models.Index(fields=["entity_type", "business_key"], name="api_impstg_key_idx"),
                ],
            },
        ),
    ]
