export type FeatureMetadataStatus = 'implemented' | 'metadata-only' | 'future-recommendation';
export type FeatureMetadataSection = 'current' | 'suggested';
type Lang = 'ru' | 'en';

type LocalizedText = Record<Lang, string>;

export interface FeatureDefinition {
  key: string;
  section: FeatureMetadataSection;
  status: FeatureMetadataStatus;
  category: LocalizedText;
  label: LocalizedText;
  shortDescription: LocalizedText;
  whyItMatters: LocalizedText;
  calculation: LocalizedText;
  sourceFields: string[];
  sourceTables: string[];
  lookbackDays: number | null;
  lookbackWindow: LocalizedText;
  thresholdDescription: LocalizedText;
  interpretationZero: LocalizedText;
  interpretationOne: LocalizedText;
  caveats?: LocalizedText;
  implementationNote?: LocalizedText;
  currentProxyFeatureKeys?: string[];
}

export interface LocalizedFeatureDefinition {
  key: string;
  section: FeatureMetadataSection;
  status: FeatureMetadataStatus;
  category: string;
  label: string;
  shortDescription: string;
  whyItMatters: string;
  calculation: string;
  sourceFields: string[];
  sourceTables: string[];
  lookbackDays: number | null;
  lookbackWindow: string;
  thresholdDescription: string;
  interpretationZero: string;
  interpretationOne: string;
  caveats?: string;
  implementationNote?: string;
  currentProxyFeatureKeys?: string[];
}

const historyWindow = { ru: 'Вся доступная история покупок.', en: 'Full available purchase history.' };
const sparkWindow = (days: number): LocalizedText => ({
  ru: `Последние ${days} дней относительно current_timestamp() внутри Spark.`,
  en: `Last ${days} days relative to Spark current_timestamp().`,
});

const currentTables = ['customers_mart', 'purchases_mart'];
const itemTables = ['customers_mart', 'purchase_items_mart', 'products_mart'];
const f = <T extends FeatureDefinition>(value: T) => value;

const explicitCurrentDefinitions: FeatureDefinition[] = [
  f({
    key: 'recurrent_buyer',
    section: 'current',
    status: 'implemented',
    category: { ru: 'Поведение', en: 'Behavior' },
    label: { ru: 'Повторный покупатель', en: 'Recurrent buyer' },
    shortDescription: { ru: 'Больше двух покупок за последние 30 дней.', en: 'More than two purchases in the last 30 days.' },
    whyItMatters: { ru: 'Отделяет разовую недавнюю активность от повторяемого паттерна.', en: 'Separates one-off recent activity from a repeating pattern.' },
    calculation: { ru: 'Признак = 1, если purchases_last_30d > 2.', en: 'The feature is 1 when purchases_last_30d > 2.' },
    sourceFields: ['purchases_mart.customer_id', 'purchases_mart.purchase_dt'],
    sourceTables: currentTables,
    lookbackDays: 30,
    lookbackWindow: sparkWindow(30),
    thresholdDescription: { ru: 'Строго больше 2 покупок.', en: 'Strictly more than 2 purchases.' },
    interpretationZero: { ru: 'За 30 дней было не более двух покупок.', en: 'There were two or fewer purchases in the last 30 days.' },
    interpretationOne: { ru: 'За 30 дней было больше двух покупок.', en: 'There were more than two purchases in the last 30 days.' },
  }),
  f({
    key: 'delivery_user',
    section: 'current',
    status: 'implemented',
    category: { ru: 'Доставка', en: 'Delivery' },
    label: { ru: 'Пользователь доставки', en: 'Delivery user' },
    shortDescription: { ru: 'Хотя бы одна доставка за всю историю.', en: 'At least one delivery in the full history.' },
    whyItMatters: { ru: 'Показывает знакомство клиента с delivery-каналом.', en: 'Shows whether the customer is familiar with the delivery channel.' },
    calculation: { ru: 'Признак = 1, если delivery_any > 0.', en: 'The feature is 1 when delivery_any > 0.' },
    sourceFields: ['purchases_mart.customer_id', 'purchases_mart.is_delivery'],
    sourceTables: currentTables,
    lookbackDays: null,
    lookbackWindow: historyWindow,
    thresholdDescription: { ru: 'Хотя бы одна доставка за всё время.', en: 'At least one delivery in the full history.' },
    interpretationZero: { ru: 'В истории доставок нет.', en: 'There are no deliveries in the history.' },
    interpretationOne: { ru: 'В истории есть хотя бы одна доставка.', en: 'There is at least one delivery in the history.' },
    caveats: { ru: 'Это факт наличия доставки, а не её доля.', en: 'This is a presence flag, not a delivery share.' },
  }),
  f({
    key: 'bulk_buyer',
    section: 'current',
    status: 'implemented',
    category: { ru: 'Чек', en: 'Basket amount' },
    label: { ru: 'Покупатель с крупными покупками', en: 'Bulk buyer' },
    shortDescription: { ru: 'Средний чек клиента строго больше 1000.', en: 'Average basket is strictly above 1000.' },
    whyItMatters: { ru: 'Выделяет клиентов с дорогими или объёмными корзинами.', en: 'Highlights customers with expensive or large baskets.' },
    calculation: { ru: 'Признак = 1, если avg_total_amount > 1000 и purchases_all_time > 0.', en: 'The feature is 1 when avg_total_amount > 1000 and purchases_all_time > 0.' },
    sourceFields: ['purchases_mart.customer_id', 'purchases_mart.total_amount'],
    sourceTables: currentTables,
    lookbackDays: null,
    lookbackWindow: historyWindow,
    thresholdDescription: { ru: 'Средний чек > 1000.', en: 'Average basket > 1000.' },
    interpretationZero: { ru: 'Средний чек 1000 и ниже либо покупок нет.', en: 'Average basket is 1000 or below, or there are no purchases.' },
    interpretationOne: { ru: 'Средний чек клиента выше 1000.', en: 'The customer average basket is above 1000.' },
  }),
  f({
    key: 'low_cost_buyer',
    section: 'current',
    status: 'implemented',
    category: { ru: 'Чек', en: 'Basket amount' },
    label: { ru: 'Покупатель с низким средним чеком', en: 'Low-cost buyer' },
    shortDescription: { ru: 'Средний чек клиента строго меньше 200.', en: 'Average basket is strictly below 200.' },
    whyItMatters: { ru: 'Даёт грубый сигнал low-ticket сегмента.', en: 'Provides a coarse low-ticket signal.' },
    calculation: { ru: 'Признак = 1, если avg_total_amount < 200 и purchases_all_time > 0.', en: 'The feature is 1 when avg_total_amount < 200 and purchases_all_time > 0.' },
    sourceFields: ['purchases_mart.customer_id', 'purchases_mart.total_amount'],
    sourceTables: currentTables,
    lookbackDays: null,
    lookbackWindow: historyWindow,
    thresholdDescription: { ru: 'Средний чек < 200.', en: 'Average basket < 200.' },
    interpretationZero: { ru: 'Средний чек 200 и выше либо покупок нет.', en: 'Average basket is 200 or above, or there are no purchases.' },
    interpretationOne: { ru: 'Средний чек клиента ниже 200.', en: 'The customer average basket is below 200.' },
  }),
  f({
    key: 'prefers_cash',
    section: 'current',
    status: 'implemented',
    category: { ru: 'Оплата', en: 'Payment' },
    label: { ru: 'Предпочитает наличные', en: 'Prefers cash' },
    shortDescription: { ru: 'Не менее 70% покупок оплачены наличными.', en: 'At least 70% of purchases are paid in cash.' },
    whyItMatters: { ru: 'Даёт простой платёжный профиль клиента.', en: 'Provides a simple payment profile.' },
    calculation: { ru: 'Признак = 1, если cash_share >= 0.7 и purchases_all_time > 0.', en: 'The feature is 1 when cash_share >= 0.7 and purchases_all_time > 0.' },
    sourceFields: ['purchases_mart.customer_id', 'purchases_mart.payment_method'],
    sourceTables: currentTables,
    lookbackDays: null,
    lookbackWindow: historyWindow,
    thresholdDescription: { ru: 'Не менее 70% покупок наличными.', en: 'At least 70% of purchases paid in cash.' },
    interpretationZero: { ru: 'Явного перевеса в пользу наличных нет.', en: 'There is no clear cash preference.' },
    interpretationOne: { ru: 'Большинство покупок оплачено наличными.', en: 'Most purchases are paid in cash.' },
  }),
  f({
    key: 'prefers_card',
    section: 'current',
    status: 'implemented',
    category: { ru: 'Оплата', en: 'Payment' },
    label: { ru: 'Предпочитает карту', en: 'Prefers card' },
    shortDescription: { ru: 'Не менее 70% покупок оплачены картой.', en: 'At least 70% of purchases are paid by card.' },
    whyItMatters: { ru: 'Показывает более цифровой платёжный паттерн.', en: 'Shows a more digital payment pattern.' },
    calculation: { ru: 'Признак = 1, если card_share >= 0.7 и purchases_all_time > 0.', en: 'The feature is 1 when card_share >= 0.7 and purchases_all_time > 0.' },
    sourceFields: ['purchases_mart.customer_id', 'purchases_mart.payment_method'],
    sourceTables: currentTables,
    lookbackDays: null,
    lookbackWindow: historyWindow,
    thresholdDescription: { ru: 'Не менее 70% покупок картой.', en: 'At least 70% of purchases paid by card.' },
    interpretationZero: { ru: 'Явного перевеса в пользу карты нет.', en: 'There is no clear card preference.' },
    interpretationOne: { ru: 'Большинство покупок оплачено картой.', en: 'Most purchases are paid by card.' },
  }),
  f({
    key: 'weekend_shopper',
    section: 'current',
    status: 'implemented',
    category: { ru: 'Время', en: 'Time' },
    label: { ru: 'Покупает в выходные', en: 'Weekend shopper' },
    shortDescription: { ru: 'Не менее 60% покупок приходится на выходные.', en: 'At least 60% of purchases happen on weekends.' },
    whyItMatters: { ru: 'Показывает недельный ритм покупок.', en: 'Shows a weekly shopping rhythm.' },
    calculation: { ru: 'Признак = 1, если weekend_share >= 0.6 и purchases_all_time > 0.', en: 'The feature is 1 when weekend_share >= 0.6 and purchases_all_time > 0.' },
    sourceFields: ['purchases_mart.customer_id', 'purchases_mart.purchase_dt'],
    sourceTables: currentTables,
    lookbackDays: null,
    lookbackWindow: historyWindow,
    thresholdDescription: { ru: 'Не менее 60% покупок в выходные.', en: 'At least 60% of purchases on weekends.' },
    interpretationZero: { ru: 'Выходной паттерн не доминирует.', en: 'Weekend behavior is not dominant.' },
    interpretationOne: { ru: 'Покупки смещены к выходным.', en: 'Purchases are shifted toward weekends.' },
  }),
  f({
    key: 'weekday_shopper',
    section: 'current',
    status: 'implemented',
    category: { ru: 'Время', en: 'Time' },
    label: { ru: 'Покупает в будни', en: 'Weekday shopper' },
    shortDescription: { ru: 'Не менее 60% покупок приходится на будни.', en: 'At least 60% of purchases happen on weekdays.' },
    whyItMatters: { ru: 'Показывает более рутинный ритм покупок.', en: 'Shows a more routine shopping rhythm.' },
    calculation: { ru: 'Признак = 1, если weekday_share >= 0.6 и purchases_all_time > 0.', en: 'The feature is 1 when weekday_share >= 0.6 and purchases_all_time > 0.' },
    sourceFields: ['purchases_mart.customer_id', 'purchases_mart.purchase_dt'],
    sourceTables: currentTables,
    lookbackDays: null,
    lookbackWindow: historyWindow,
    thresholdDescription: { ru: 'Не менее 60% покупок в будни.', en: 'At least 60% of purchases on weekdays.' },
    interpretationZero: { ru: 'Будничный паттерн не доминирует.', en: 'Weekday behavior is not dominant.' },
    interpretationOne: { ru: 'Покупки смещены к будням.', en: 'Purchases are shifted toward weekdays.' },
  }),
  f({
    key: 'night_shopper',
    section: 'current',
    status: 'implemented',
    category: { ru: 'Время', en: 'Time' },
    label: { ru: 'Делал покупки после 20:00', en: 'Shops after 20:00' },
    shortDescription: { ru: 'Не менее половины покупок сделано после 20:00.', en: 'At least half of purchases happen after 20:00.' },
    whyItMatters: { ru: 'Полезно для time-based коммуникаций.', en: 'Useful for time-based communication.' },
    calculation: { ru: 'Признак = 1, если night_share >= 0.5 и purchases_all_time > 0.', en: 'The feature is 1 when night_share >= 0.5 and purchases_all_time > 0.' },
    sourceFields: ['purchases_mart.customer_id', 'purchases_mart.purchase_dt'],
    sourceTables: currentTables,
    lookbackDays: null,
    lookbackWindow: historyWindow,
    thresholdDescription: { ru: 'Не менее 50% покупок после 20:00.', en: 'At least 50% of purchases after 20:00.' },
    interpretationZero: { ru: 'Ночной паттерн не доминирует.', en: 'Late-evening behavior is not dominant.' },
    interpretationOne: { ru: 'Не менее половины покупок после 20:00.', en: 'At least half of purchases happen after 20:00.' },
  }),
  f({
    key: 'morning_shopper',
    section: 'current',
    status: 'implemented',
    category: { ru: 'Время', en: 'Time' },
    label: { ru: 'Делал покупки до 10:00', en: 'Shops before 10:00' },
    shortDescription: { ru: 'Не менее половины покупок сделано до 10:00.', en: 'At least half of purchases happen before 10:00.' },
    whyItMatters: { ru: 'Отражает ранний ритм потребления.', en: 'Reflects an early-day shopping rhythm.' },
    calculation: { ru: 'Признак = 1, если morning_share >= 0.5 и purchases_all_time > 0.', en: 'The feature is 1 when morning_share >= 0.5 and purchases_all_time > 0.' },
    sourceFields: ['purchases_mart.customer_id', 'purchases_mart.purchase_dt'],
    sourceTables: currentTables,
    lookbackDays: null,
    lookbackWindow: historyWindow,
    thresholdDescription: { ru: 'Не менее 50% покупок до 10:00.', en: 'At least 50% of purchases before 10:00.' },
    interpretationZero: { ru: 'Утренний паттерн не доминирует.', en: 'Morning behavior is not dominant.' },
    interpretationOne: { ru: 'Не менее половины покупок до 10:00.', en: 'At least half of purchases happen before 10:00.' },
  }),
  f({
    key: 'no_purchases',
    section: 'current',
    status: 'implemented',
    category: { ru: 'Активность', en: 'Activity' },
    label: { ru: 'Нет покупок', en: 'No purchases' },
    shortDescription: { ru: 'Явно помечает клиентов без покупок в витрине.', en: 'Explicitly marks customers with no purchases in the mart.' },
    whyItMatters: { ru: 'Отделяет пустого клиента от клиента без конкретного паттерна.', en: 'Separates an empty customer from a customer with no specific pattern.' },
    calculation: { ru: 'Признак = 1, если purchases_all_time == 0.', en: 'The feature is 1 when purchases_all_time == 0.' },
    sourceFields: ['customers_mart.customer_id', 'purchases_mart.customer_id'],
    sourceTables: currentTables,
    lookbackDays: null,
    lookbackWindow: { ru: 'Вся доступная история.', en: 'Full available history.' },
    thresholdDescription: { ru: 'Ровно ноль покупок.', en: 'Exactly zero purchases.' },
    interpretationZero: { ru: 'У клиента есть хотя бы одна покупка.', en: 'The customer has at least one purchase.' },
    interpretationOne: { ru: 'У клиента нет покупок в витрине.', en: 'The customer has no purchases in the mart.' },
    caveats: { ru: 'Большинство остальных фич для такого клиента становятся 0 через coalesce-логику.', en: 'Most other features become 0 for such a customer through the coalesce logic.' },
  }),
  f({
    key: 'frequent_shopper_last_14d',
    section: 'current',
    status: 'implemented',
    category: { ru: 'Активность', en: 'Activity' },
    label: { ru: 'Частый покупатель за 14 дней', en: 'Frequent shopper in last 14d' },
    shortDescription: { ru: 'Не менее трёх покупок за последние 14 дней.', en: 'At least three purchases in the last 14 days.' },
    whyItMatters: { ru: 'Выделяет очень активных клиентов на коротком горизонте.', en: 'Highlights very active customers over a short horizon.' },
    calculation: { ru: 'Признак = 1, если purchases_last_14d >= 3.', en: 'The feature is 1 when purchases_last_14d >= 3.' },
    sourceFields: ['purchases_mart.customer_id', 'purchases_mart.purchase_dt'],
    sourceTables: currentTables,
    lookbackDays: 14,
    lookbackWindow: sparkWindow(14),
    thresholdDescription: { ru: 'Не менее 3 покупок.', en: 'At least 3 purchases.' },
    interpretationZero: { ru: 'Частота за 14 дней ниже порога.', en: 'Frequency in the 14-day window is below the threshold.' },
    interpretationOne: { ru: 'Клиент покупал часто в последние 14 дней.', en: 'The customer purchased frequently in the last 14 days.' },
  }),
  f({
    key: 'high_ticket_last_90d',
    section: 'current',
    status: 'implemented',
    category: { ru: 'Чек', en: 'Basket amount' },
    label: { ru: 'Крупный чек за 90 дней', en: 'High ticket in last 90d' },
    shortDescription: { ru: 'Хотя бы один чек за 90 дней был выше 1500.', en: 'At least one basket in the last 90 days was above 1500.' },
    whyItMatters: { ru: 'Ловит high-value сигнал даже при умеренном среднем чеке.', en: 'Captures a high-value signal even with a moderate average basket.' },
    calculation: { ru: 'Признак = 1, если max_total_amount_90d > 1500.', en: 'The feature is 1 when max_total_amount_90d > 1500.' },
    sourceFields: ['purchases_mart.customer_id', 'purchases_mart.total_amount', 'purchases_mart.purchase_dt'],
    sourceTables: currentTables,
    lookbackDays: 90,
    lookbackWindow: sparkWindow(90),
    thresholdDescription: { ru: 'Хотя бы один чек строго больше 1500.', en: 'At least one basket strictly above 1500.' },
    interpretationZero: { ru: 'За 90 дней чека выше 1500 не было.', en: 'There was no basket above 1500 in the last 90 days.' },
    interpretationOne: { ru: 'За 90 дней был хотя бы один чек выше 1500.', en: 'There was at least one basket above 1500 in the last 90 days.' },
  }),
  f({
    key: 'delivery_last_30d',
    section: 'current',
    status: 'implemented',
    category: { ru: 'Доставка', en: 'Delivery' },
    label: { ru: 'Была доставка за 30 дней', en: 'Delivery in last 30d' },
    shortDescription: { ru: 'Хотя бы одна доставка за последние 30 дней.', en: 'At least one delivery in the last 30 days.' },
    whyItMatters: { ru: 'Отделяет текущую доставочную активность от исторической.', en: 'Separates current delivery activity from historical usage.' },
    calculation: { ru: 'Признак = 1, если delivery_any_30d > 0.', en: 'The feature is 1 when delivery_any_30d > 0.' },
    sourceFields: ['purchases_mart.customer_id', 'purchases_mart.is_delivery', 'purchases_mart.purchase_dt'],
    sourceTables: currentTables,
    lookbackDays: 30,
    lookbackWindow: sparkWindow(30),
    thresholdDescription: { ru: 'Хотя бы одна доставка за 30 дней.', en: 'At least one delivery in the last 30 days.' },
    interpretationZero: { ru: 'За 30 дней доставок не было.', en: 'There were no deliveries in the last 30 days.' },
    interpretationOne: { ru: 'За 30 дней была хотя бы одна доставка.', en: 'There was at least one delivery in the last 30 days.' },
  }),
  f({
    key: 'cross_store_shopper_last_90d',
    section: 'current',
    status: 'implemented',
    category: { ru: 'Магазины', en: 'Stores' },
    label: { ru: 'Покупал в разных магазинах за 90 дней', en: 'Cross-store shopper in last 90d' },
    shortDescription: { ru: 'Минимум два магазина за последние 90 дней.', en: 'At least two stores during the last 90 days.' },
    whyItMatters: { ru: 'Показывает мобильность клиента и слабую привязку к одной точке.', en: 'Shows customer mobility and weaker attachment to one store.' },
    calculation: { ru: 'Признак = 1, если distinct_stores_90d >= 2.', en: 'The feature is 1 when distinct_stores_90d >= 2.' },
    sourceFields: ['purchases_mart.customer_id', 'purchases_mart.store_id', 'purchases_mart.purchase_dt'],
    sourceTables: currentTables,
    lookbackDays: 90,
    lookbackWindow: sparkWindow(90),
    thresholdDescription: { ru: 'Минимум 2 разных store_id.', en: 'At least 2 distinct store_id values.' },
    interpretationZero: { ru: 'Клиент покупал в одном магазине или не покупал.', en: 'The customer bought in one store only or did not buy.' },
    interpretationOne: { ru: 'Клиент покупал минимум в двух магазинах.', en: 'The customer bought in at least two stores.' },
  }),
  f({
    key: 'mixed_payment_user_last_90d',
    section: 'current',
    status: 'implemented',
    category: { ru: 'Оплата', en: 'Payment' },
    label: { ru: 'Использовал смешанную оплату за 90 дней', en: 'Used mixed payments in last 90d' },
    shortDescription: { ru: 'За 90 дней клиент использовал и наличные, и карту.', en: 'During the last 90 days the customer used both cash and card.' },
    whyItMatters: { ru: 'Даёт понятный сигнал гибкого платёжного поведения.', en: 'Provides a clear signal of flexible payment behavior.' },
    calculation: { ru: 'Признак = 1, если used_cash_90d = 1 и used_card_90d = 1.', en: 'The feature is 1 when used_cash_90d = 1 and used_card_90d = 1.' },
    sourceFields: ['purchases_mart.customer_id', 'purchases_mart.payment_method', 'purchases_mart.purchase_dt'],
    sourceTables: currentTables,
    lookbackDays: 90,
    lookbackWindow: sparkWindow(90),
    thresholdDescription: { ru: 'Хотя бы одна наличная и одна карточная покупка.', en: 'At least one cash and one card purchase.' },
    interpretationZero: { ru: 'Использовался только один из двух способов или покупок не было.', en: 'Only one method was used or there were no purchases.' },
    interpretationOne: { ru: 'Клиент использовал и наличные, и карту.', en: 'The customer used both cash and card.' },
  }),
  f({
    key: 'high_quantity_buyer_last_30d',
    section: 'current',
    status: 'implemented',
    category: { ru: 'Корзина', en: 'Basket' },
    label: { ru: 'Покупал большими объёмами за 30 дней', en: 'High quantity buyer in last 30d' },
    shortDescription: { ru: 'Хотя бы одна позиция количеством больше двух единиц за 30 дней.', en: 'At least one line item above quantity two in the last 30 days.' },
    whyItMatters: { ru: 'Показывает склонность покупать некоторые товары большими объёмами.', en: 'Shows a tendency to buy some items in larger quantities.' },
    calculation: { ru: 'Признак = 1, если есть строка с quantity > 2 и is_last_30d = 1.', en: 'The feature is 1 when there is a row with quantity > 2 and is_last_30d = 1.' },
    sourceFields: ['purchase_items_mart.customer_id', 'purchase_items_mart.quantity', 'purchase_items_mart.purchase_dt'],
    sourceTables: ['customers_mart', 'purchase_items_mart'],
    lookbackDays: 30,
    lookbackWindow: sparkWindow(30),
    thresholdDescription: { ru: 'Хотя бы одна позиция с quantity > 2.', en: 'At least one line item with quantity > 2.' },
    interpretationZero: { ru: 'Покупок количеством больше 2 не было.', en: 'No line item above quantity 2 appeared.' },
    interpretationOne: { ru: 'Была хотя бы одна покупка количеством больше 2.', en: 'There was at least one line item above quantity 2.' },
  }),
  f({
    key: 'vegetarian_profile',
    section: 'current',
    status: 'implemented',
    category: { ru: 'Профиль', en: 'Profile' },
    label: { ru: 'Вегетарианский профиль', en: 'Vegetarian profile' },
    shortDescription: { ru: 'Есть plant-сигнал и нет meat-сигнала за 90 дней.', en: 'There is a plant signal and no meat signal in the last 90 days.' },
    whyItMatters: { ru: 'Даёт интерпретируемый food-profile сигнал без сложной модели категорий.', en: 'Provides an interpretable food-profile signal without a complex category model.' },
    calculation: { ru: 'Признак = 1, если has_meat_last_90d = 0, has_plant_last_90d = 1 и purchases_all_time > 0.', en: 'The feature is 1 when has_meat_last_90d = 0, has_plant_last_90d = 1 and purchases_all_time > 0.' },
    sourceFields: ['purchase_items_mart.customer_id', 'purchase_items_mart.category / group', 'purchase_items_mart.purchase_dt', 'products_mart.group', 'purchases_mart.customer_id'],
    sourceTables: ['customers_mart', 'purchase_items_mart', 'products_mart', 'purchases_mart'],
    lookbackDays: 90,
    lookbackWindow: sparkWindow(90),
    thresholdDescription: { ru: 'Нет meat-сигнала, есть plant-сигнал, клиент не пустой.', en: 'No meat signal, plant signal present, and the customer is not empty.' },
    interpretationZero: { ru: 'Есть meat-сигнал, нет plant-сигнала или покупок нет.', en: 'There is a meat signal, there is no plant signal, or there are no purchases.' },
    interpretationOne: { ru: 'Виден plant-only паттерн без meat-сигнала.', en: 'A plant-only pattern without a meat signal is visible.' },
    caveats: { ru: 'Это осторожный аналитический proxy, а не реальная диетологическая классификация.', en: 'This is a cautious analytical proxy, not a true nutritional classification.' },
  }),
];

const categoryMeta: Record<string, { ru: string; en: string; sourceField: string; thresholdRu: string; thresholdEn: string }> = {
  milk: { ru: 'молочные', en: 'dairy', sourceField: 'products_mart.category_raw ~ "молоч|dairy"', thresholdRu: 'Хотя бы одна подходящая позиция.', thresholdEn: 'At least one matching item.' },
  meat: { ru: 'мясо', en: 'meat', sourceField: 'products_mart.category_raw ~ "мяс|рыб|яйц|protein|..."', thresholdRu: 'Хотя бы одна подходящая позиция.', thresholdEn: 'At least one matching item.' },
  fruits: { ru: 'фрукты', en: 'fruits', sourceField: 'products_mart.category_raw ~ "фрукт|fruit"', thresholdRu: 'Хотя бы одна подходящая позиция.', thresholdEn: 'At least one matching item.' },
  vegetables: { ru: 'овощи', en: 'vegetables', sourceField: 'products_mart.category_raw ~ "овощ|vegetable"', thresholdRu: 'Хотя бы одна подходящая позиция.', thresholdEn: 'At least one matching item.' },
  bakery: { ru: 'выпечку', en: 'bakery', sourceField: 'products_mart.category_raw ~ "выпеч|bakery|bread"', thresholdRu: 'Хотя бы одна подходящая позиция.', thresholdEn: 'At least one matching item.' },
  organic: { ru: 'органик', en: 'organic', sourceField: 'purchase_items_mart.is_organic == 1', thresholdRu: 'Хотя бы одна organic-позиция.', thresholdEn: 'At least one organic item.' },
};

function buildPatternDefinition(key: string): FeatureDefinition | null {
  const purchasesMatch = key.match(/^has_purchases_last_(7|14|30|90)d$/);
  if (purchasesMatch) {
    const days = Number(purchasesMatch[1]);
    return {
      key,
      section: 'current',
      status: 'implemented',
      category: { ru: 'Активность', en: 'Activity' },
      label: { ru: `Есть покупки за ${days} дней`, en: `Has purchases in last ${days}d` },
      shortDescription: { ru: `Хотя бы одна покупка за последние ${days} дней.`, en: `At least one purchase in the last ${days} days.` },
      whyItMatters: { ru: 'Это базовый флаг недавней активности.', en: 'This is a basic recent-activity flag.' },
      calculation: { ru: `Признак = 1, если purchases_last_${days}d > 0.`, en: `The feature is 1 when purchases_last_${days}d > 0.` },
      sourceFields: ['purchases_mart.customer_id', 'purchases_mart.purchase_dt'],
      sourceTables: currentTables,
      lookbackDays: days,
      lookbackWindow: sparkWindow(days),
      thresholdDescription: { ru: 'Хотя бы одна покупка в окне.', en: 'At least one purchase in the window.' },
      interpretationZero: { ru: `За последние ${days} дней покупок нет.`, en: `There are no purchases in the last ${days} days.` },
      interpretationOne: { ru: `За последние ${days} дней есть хотя бы одна покупка.`, en: `There is at least one purchase in the last ${days} days.` },
    };
  }

  const categoryMatch = key.match(/^bought_(milk|meat|fruits|vegetables|bakery|organic)_last_(7|30|90)d$/);
  if (categoryMatch) {
    const [, categoryKey, daysToken] = categoryMatch;
    const days = Number(daysToken);
    const meta = categoryMeta[categoryKey];
    return {
      key,
      section: 'current',
      status: 'implemented',
      category: { ru: 'Категории', en: 'Categories' },
      label: { ru: `Покупал ${meta.ru} за ${days} дней`, en: `Bought ${meta.en} in last ${days}d` },
      shortDescription: { ru: `Хотя бы одна покупка категории за последние ${days} дней.`, en: `At least one ${meta.en} purchase in the last ${days} days.` },
      whyItMatters: { ru: 'Даёт быстрый сигнал интереса к товарной группе.', en: 'Provides a quick signal of interest in a product group.' },
      calculation: { ru: `Признак = 1, если has_${categoryKey}_last_${days}d > 0.`, en: `The feature is 1 when has_${categoryKey}_last_${days}d > 0.` },
      sourceFields: ['purchase_items_mart.customer_id', 'purchase_items_mart.purchase_dt', meta.sourceField],
      sourceTables: itemTables,
      lookbackDays: days,
      lookbackWindow: sparkWindow(days),
      thresholdDescription: { ru: meta.thresholdRu, en: meta.thresholdEn },
      interpretationZero: { ru: `За последние ${days} дней категория не встречалась.`, en: `${meta.en} did not appear in the last ${days} days.` },
      interpretationOne: { ru: `За последние ${days} дней была хотя бы одна такая покупка.`, en: `There was at least one ${meta.en} purchase in the last ${days} days.` },
      caveats: { ru: 'Категория определяется через regex по category_raw и fallback на product_group.', en: 'The category is detected with regex over category_raw and a product_group fallback.' },
    };
  }

  return null;
}

export const suggestedFeatureDefinitions: FeatureDefinition[] = [
  f({
    key: 'purchase_frequency_30d',
    section: 'suggested',
    status: 'future-recommendation',
    category: { ru: 'Активность', en: 'Activity' },
    label: { ru: 'Частота покупок за 30 дней', en: 'Purchase frequency 30d' },
    shortDescription: { ru: 'Нормализованная интенсивность покупок за последний месяц.', en: 'Normalized shopping intensity over the last month.' },
    whyItMatters: { ru: 'Лучше различает 1, 2, 5 и 10 покупок, чем бинарные флаги.', en: 'It distinguishes 1, 2, 5 and 10 purchases better than binary flags.' },
    calculation: { ru: 'Например, purchases_last_30d / 30 или z-score внутри когорты.', en: 'For example, purchases_last_30d / 30 or a cohort z-score.' },
    sourceFields: ['purchases_mart.customer_id', 'purchases_mart.purchase_dt'],
    sourceTables: currentTables,
    lookbackDays: 30,
    lookbackWindow: sparkWindow(30),
    thresholdDescription: { ru: 'Обычно полезнее как числовой score, а не бинарный флаг.', en: 'Usually more useful as a numeric score than a binary flag.' },
    interpretationZero: { ru: 'Очень низкая частота.', en: 'Very low frequency.' },
    interpretationOne: { ru: 'Высокая частота относительно выбранной шкалы.', en: 'High frequency relative to the chosen scale.' },
    implementationNote: { ru: 'Рекомендуется как следующий ETL score.', en: 'Recommended as the next ETL score.' },
  }),
  f({
    key: 'avg_basket_volatility',
    section: 'suggested',
    status: 'future-recommendation',
    category: { ru: 'Чек', en: 'Basket amount' },
    label: { ru: 'Волатильность среднего чека', en: 'Average basket volatility' },
    shortDescription: { ru: 'Разброс сумм заказов клиента во времени.', en: 'Spread of order amounts over time.' },
    whyItMatters: { ru: 'Помогает понять, насколько клиент стабилен или импульсивен по расходам.', en: 'Helps separate stable and impulsive spenders.' },
    calculation: { ru: 'Например, stddev(total_amount) или coefficient of variation по клиенту.', en: 'For example, stddev(total_amount) or coefficient of variation per customer.' },
    sourceFields: ['purchases_mart.customer_id', 'purchases_mart.total_amount'],
    sourceTables: currentTables,
    lookbackDays: 90,
    lookbackWindow: sparkWindow(90),
    thresholdDescription: { ru: 'Чаще полезен как числовой признак.', en: 'Usually better as a numeric feature.' },
    interpretationZero: { ru: 'Стабильные чеки.', en: 'Stable basket amounts.' },
    interpretationOne: { ru: 'Сильно плавающие чеки.', en: 'Highly volatile basket amounts.' },
  }),
  f({
    key: 'recency_score',
    section: 'suggested',
    status: 'future-recommendation',
    category: { ru: 'Активность', en: 'Activity' },
    label: { ru: 'Score давности последней покупки', en: 'Recency score' },
    shortDescription: { ru: 'Чем свежее последняя покупка, тем выше score.', en: 'The more recent the last purchase, the higher the score.' },
    whyItMatters: { ru: 'Это сильный сигнал для CRM и retention-задач.', en: 'This is a strong signal for CRM and retention.' },
    calculation: { ru: 'Days since last purchase, преобразованные в шкалу 0..1 или в бины.', en: 'Days since last purchase transformed into a 0..1 scale or bins.' },
    sourceFields: ['purchases_mart.customer_id', 'purchases_mart.purchase_dt'],
    sourceTables: currentTables,
    lookbackDays: null,
    lookbackWindow: historyWindow,
    thresholdDescription: { ru: 'Пороги можно задать, например, 7/30/90 дней.', en: 'Thresholds can be set, for example, at 7/30/90 days.' },
    interpretationZero: { ru: 'Покупка была давно.', en: 'The last purchase was a long time ago.' },
    interpretationOne: { ru: 'Покупка была недавно.', en: 'The last purchase was recent.' },
  }),
  f({
    key: 'category_diversity_score',
    section: 'suggested',
    status: 'future-recommendation',
    category: { ru: 'Категории', en: 'Categories' },
    label: { ru: 'Разнообразие категорий', en: 'Category diversity score' },
    shortDescription: { ru: 'Сколько разных категорий покупает клиент.', en: 'How many distinct categories the customer buys.' },
    whyItMatters: { ru: 'Отличает миссионные корзины от очень узких привычек.', en: 'Separates mission baskets from narrow habits.' },
    calculation: { ru: 'Distinct count категорий или групп на окне 30/90 дней.', en: 'Distinct count of categories or groups in a 30/90-day window.' },
    sourceFields: ['purchase_items_mart.customer_id', 'products_mart.category_raw', 'products_mart.product_group'],
    sourceTables: itemTables,
    lookbackDays: 90,
    lookbackWindow: sparkWindow(90),
    thresholdDescription: { ru: 'Можно биннизировать по 1-2 / 3-5 / 6+ категориям.', en: 'Can be bucketed into 1-2 / 3-5 / 6+ categories.' },
    interpretationZero: { ru: 'Низкое разнообразие категорий.', en: 'Low category diversity.' },
    interpretationOne: { ru: 'Высокое разнообразие категорий.', en: 'High category diversity.' },
  }),
  f({
    key: 'promo_sensitivity',
    section: 'suggested',
    status: 'metadata-only',
    category: { ru: 'Цена', en: 'Price sensitivity' },
    label: { ru: 'Чувствительность к промо', en: 'Promo sensitivity' },
    shortDescription: { ru: 'Proxy для склонности реагировать на скидочные паттерны.', en: 'A proxy for reacting to discount-like patterns.' },
    whyItMatters: { ru: 'Полезно для персональных акций и price segmentation.', en: 'Useful for personal promotions and price segmentation.' },
    calculation: { ru: 'Без явного discount-поля можно использовать low_cost_buyer и изменения частоты/чека.', en: 'Without an explicit discount field, use low_cost_buyer plus changes in frequency and basket amount.' },
    sourceFields: ['purchases_mart.total_amount', 'purchases_mart.purchase_dt'],
    sourceTables: currentTables,
    lookbackDays: 90,
    lookbackWindow: sparkWindow(90),
    thresholdDescription: { ru: 'Лучше начинать как score.', en: 'Better introduced as a score.' },
    interpretationZero: { ru: 'Слабая реакция на price-like сигналы.', en: 'Weak reaction to price-like signals.' },
    interpretationOne: { ru: 'Высокая вероятная чувствительность к цене.', en: 'Likely high price sensitivity.' },
  }),
  f({
    key: 'delivery_dependency',
    section: 'suggested',
    status: 'metadata-only',
    category: { ru: 'Доставка', en: 'Delivery' },
    label: { ru: 'Зависимость от доставки', en: 'Delivery dependency' },
    shortDescription: { ru: 'Доля заказов, оформленных как доставка.', en: 'Share of orders placed as delivery.' },
    whyItMatters: { ru: 'Сильнее бинарного факта доставки: показывает степень зависимости от канала.', en: 'Stronger than a binary delivery flag because it captures dependency on the channel.' },
    calculation: { ru: 'delivery_orders / all_orders за окно 30/90 дней.', en: 'delivery_orders / all_orders over a 30/90-day window.' },
    sourceFields: ['purchases_mart.customer_id', 'purchases_mart.purchase_dt', 'purchases_mart.is_delivery'],
    sourceTables: currentTables,
    lookbackDays: 90,
    lookbackWindow: sparkWindow(90),
    thresholdDescription: { ru: 'Можно вводить бины вроде 0%, 1-49%, 50%+.', en: 'Can be bucketed into 0%, 1-49%, 50%+.' },
    interpretationZero: { ru: 'Доставка не доминирует.', en: 'Delivery does not dominate.' },
    interpretationOne: { ru: 'Сильная зависимость от доставки.', en: 'Strong delivery dependency.' },
    currentProxyFeatureKeys: ['delivery_user', 'delivery_last_30d'],
  }),
  f({
    key: 'store_switching_intensity',
    section: 'suggested',
    status: 'implemented',
    category: { ru: 'Магазины', en: 'Stores' },
    label: { ru: 'Интенсивность переключения магазинов', en: 'Store switching intensity' },
    shortDescription: { ru: 'Описывает, насколько активно клиент меняет магазины.', en: 'Describes how actively the customer switches stores.' },
    whyItMatters: { ru: 'Полезно для понимания лояльности к точке продаж и географической гибкости.', en: 'Useful for store loyalty and geographic flexibility analysis.' },
    calculation: { ru: 'Упрощённый текущий proxy уже есть: distinct_stores_90d >= 2.', en: 'A simplified proxy already exists: distinct_stores_90d >= 2.' },
    sourceFields: ['purchases_mart.customer_id', 'purchases_mart.purchase_dt', 'purchases_mart.store_id'],
    sourceTables: currentTables,
    lookbackDays: 90,
    lookbackWindow: sparkWindow(90),
    thresholdDescription: { ru: 'Текущий proxy использует порог 2 магазина.', en: 'The current proxy uses a threshold of 2 stores.' },
    interpretationZero: { ru: 'Слабое переключение или один основной магазин.', en: 'Weak switching or one main store.' },
    interpretationOne: { ru: 'Есть заметное переключение между магазинами.', en: 'There is noticeable switching across stores.' },
    implementationNote: { ru: 'Сейчас это покрывает cross_store_shopper_last_90d.', en: 'Currently covered by cross_store_shopper_last_90d.' },
    currentProxyFeatureKeys: ['cross_store_shopper_last_90d'],
  }),
  f({
    key: 'payment_mixed_user',
    section: 'suggested',
    status: 'implemented',
    category: { ru: 'Оплата', en: 'Payment' },
    label: { ru: 'Регулярно использует несколько способов оплаты', en: 'Payment mixed user' },
    shortDescription: { ru: 'Клиент не привязан к одному способу оплаты.', en: 'The customer is not tied to a single payment method.' },
    whyItMatters: { ru: 'Помогает отличать гибкий платёжный паттерн от жёсткого предпочтения.', en: 'Helps separate flexible payment behavior from strict preference.' },
    calculation: { ru: 'Текущий proxy уже есть: использовал и наличные, и карту за 90 дней.', en: 'A current proxy already exists: both cash and card used in the last 90 days.' },
    sourceFields: ['purchases_mart.customer_id', 'purchases_mart.purchase_dt', 'purchases_mart.payment_method'],
    sourceTables: currentTables,
    lookbackDays: 90,
    lookbackWindow: sparkWindow(90),
    thresholdDescription: { ru: 'Оба метода должны встретиться хотя бы раз.', en: 'Both methods must appear at least once.' },
    interpretationZero: { ru: 'Платёжный паттерн однотипный.', en: 'Payment behavior is one-sided.' },
    interpretationOne: { ru: 'Клиент реально использует несколько типов оплаты.', en: 'The customer really uses multiple payment types.' },
    implementationNote: { ru: 'Сейчас покрывается mixed_payment_user_last_90d.', en: 'Currently covered by mixed_payment_user_last_90d.' },
    currentProxyFeatureKeys: ['mixed_payment_user_last_90d'],
  }),
  f({
    key: 'late_month_shopper',
    section: 'suggested',
    status: 'future-recommendation',
    category: { ru: 'Время', en: 'Time' },
    label: { ru: 'Покупает в конце месяца', en: 'Late month shopper' },
    shortDescription: { ru: 'Покупки концентрируются в последних днях месяца.', en: 'Purchases concentrate in the final days of the month.' },
    whyItMatters: { ru: 'Может быть связано с зарплатным циклом и cash-flow клиента.', en: 'May be linked to salary cycles and customer cash flow.' },
    calculation: { ru: 'Доля покупок в днях 25-31 месяца относительно общего числа покупок.', en: 'Share of purchases made on days 25-31 of the month.' },
    sourceFields: ['purchases_mart.customer_id', 'purchases_mart.purchase_dt'],
    sourceTables: currentTables,
    lookbackDays: 90,
    lookbackWindow: sparkWindow(90),
    thresholdDescription: { ru: 'Например, >= 50% покупок в конце месяца.', en: 'For example, >= 50% of purchases near month-end.' },
    interpretationZero: { ru: 'Явной концентрации в конце месяца нет.', en: 'There is no clear month-end concentration.' },
    interpretationOne: { ru: 'Покупки смещены к концу месяца.', en: 'Purchases are concentrated near month-end.' },
  }),
  f({
    key: 'churn_risk_proxy',
    section: 'suggested',
    status: 'future-recommendation',
    category: { ru: 'Retention', en: 'Retention' },
    label: { ru: 'Proxy риска оттока', en: 'Churn risk proxy' },
    shortDescription: { ru: 'Сигнал риска оттока на основе давности и снижения частоты.', en: 'A churn-risk signal based on recency and declining frequency.' },
    whyItMatters: { ru: 'Один из самых полезных operational-признаков для CRM.', en: 'One of the most useful operational features for CRM.' },
    calculation: { ru: 'Комбинация recency_score, purchases_last_30d и более длинной истории.', en: 'A combination of recency_score, purchases_last_30d and a longer historical baseline.' },
    sourceFields: ['purchases_mart.customer_id', 'purchases_mart.purchase_dt'],
    sourceTables: currentTables,
    lookbackDays: 90,
    lookbackWindow: sparkWindow(90),
    thresholdDescription: { ru: 'Лучше стартовать как score, а не бинарный флаг.', en: 'Best introduced as a score rather than a binary flag.' },
    interpretationZero: { ru: 'Низкий риск оттока.', en: 'Low churn risk.' },
    interpretationOne: { ru: 'Высокий риск оттока.', en: 'High churn risk.' },
  }),
  f({
    key: 'high_value_recent_customer',
    section: 'suggested',
    status: 'metadata-only',
    category: { ru: 'Чек', en: 'Basket amount' },
    label: { ru: 'Высокая ценность в недавнем окне', en: 'High value recent customer' },
    shortDescription: { ru: 'Клиент тратит много в коротком недавнем окне.', en: 'The customer spends a lot in a short recent window.' },
    whyItMatters: { ru: 'Полезно для персонализации и VIP-like сегментации.', en: 'Useful for personalization and VIP-like segmentation.' },
    calculation: { ru: 'Например, sum_total_amount_30d > порога или max_total_amount_30d > порога.', en: 'For example, sum_total_amount_30d above a threshold or max_total_amount_30d above a threshold.' },
    sourceFields: ['purchases_mart.customer_id', 'purchases_mart.purchase_dt', 'purchases_mart.total_amount'],
    sourceTables: currentTables,
    lookbackDays: 30,
    lookbackWindow: sparkWindow(30),
    thresholdDescription: { ru: 'Порог лучше калибровать на реальных данных.', en: 'The threshold should be calibrated on real data.' },
    interpretationZero: { ru: 'Недавняя ценность не выделяется.', en: 'Recent value is not outstanding.' },
    interpretationOne: { ru: 'Недавний вклад клиента в выручку высокий.', en: 'Recent customer value is high.' },
    currentProxyFeatureKeys: ['high_ticket_last_90d', 'bulk_buyer'],
  }),
  f({
    key: 'habitual_time_buyer',
    section: 'suggested',
    status: 'implemented',
    category: { ru: 'Время', en: 'Time' },
    label: { ru: 'Привычный покупатель по времени', en: 'Habitual time buyer' },
    shortDescription: { ru: 'Клиент стабильно покупает в одном временном диапазоне.', en: 'The customer consistently buys in one time band.' },
    whyItMatters: { ru: 'Это удобно для выбора слотов коммуникации и прогноза спроса.', en: 'Useful for communication timing and demand planning.' },
    calculation: { ru: 'Текущий продукт уже частично покрывает этот смысл через morning_shopper и night_shopper.', en: 'The current product already partially covers this idea through morning_shopper and night_shopper.' },
    sourceFields: ['purchases_mart.customer_id', 'purchases_mart.purchase_dt'],
    sourceTables: currentTables,
    lookbackDays: null,
    lookbackWindow: historyWindow,
    thresholdDescription: { ru: 'В текущих proxy-версиях используется порог 50% доли.', en: 'Current proxy versions use a 50% share threshold.' },
    interpretationZero: { ru: 'Сильная временная привычка не видна.', en: 'No strong time habit is visible.' },
    interpretationOne: { ru: 'Есть явная концентрация в одном временном диапазоне.', en: 'There is clear concentration in a specific time band.' },
    currentProxyFeatureKeys: ['morning_shopper', 'night_shopper'],
  }),
  f({
    key: 'loyalty_gap',
    section: 'suggested',
    status: 'future-recommendation',
    category: { ru: 'Лояльность', en: 'Loyalty' },
    label: { ru: 'Разрыв лояльности', en: 'Loyalty gap' },
    shortDescription: { ru: 'Много покупок, но нет устойчивости по магазину, времени или категориям.', en: 'Many purchases but little consistency across store, time, or category behavior.' },
    whyItMatters: { ru: 'Помогает найти активных, но нестабильных клиентов.', en: 'Helps find active but unstable customers.' },
    calculation: { ru: 'Комбинация частоты с отсутствием устойчивых паттернов.', en: 'A combination of frequency with the absence of stable patterns.' },
    sourceFields: ['purchases_mart.customer_id', 'purchases_mart.purchase_dt', 'purchases_mart.store_id', 'purchases_mart.payment_method'],
    sourceTables: currentTables,
    lookbackDays: 90,
    lookbackWindow: sparkWindow(90),
    thresholdDescription: { ru: 'Требует аккуратной бизнес-калибровки.', en: 'Requires careful business calibration.' },
    interpretationZero: { ru: 'Лояльностный профиль выглядит ровнее.', en: 'The loyalty profile looks more stable.' },
    interpretationOne: { ru: 'Есть разрыв между активностью и устойчивостью.', en: 'There is a gap between activity and consistency.' },
  }),
  f({
    key: 'basket_consistency',
    section: 'suggested',
    status: 'future-recommendation',
    category: { ru: 'Корзина', en: 'Basket' },
    label: { ru: 'Стабильность корзины', en: 'Basket consistency' },
    shortDescription: { ru: 'Насколько одинаков по размеру и сумме типичный чек клиента.', en: 'How consistent the customer basket is in size and amount.' },
    whyItMatters: { ru: 'Полезно для replenishment-паттернов и автопрогноза спроса.', en: 'Useful for replenishment patterns and automated demand planning.' },
    calculation: { ru: 'Низкая вариативность quantity и total_amount по клиенту.', en: 'Low variability of quantity and total_amount per customer.' },
    sourceFields: ['purchase_items_mart.quantity', 'purchases_mart.total_amount'],
    sourceTables: ['purchase_items_mart', 'purchases_mart'],
    lookbackDays: 90,
    lookbackWindow: sparkWindow(90),
    thresholdDescription: { ru: 'Часто лучше выражать как score, чем как бинарный флаг.', en: 'Often better expressed as a score than a binary flag.' },
    interpretationZero: { ru: 'Корзина заметно плавает.', en: 'The basket varies noticeably.' },
    interpretationOne: { ru: 'Корзина относительно стабильна.', en: 'The basket is relatively stable.' },
  }),
  f({
    key: 'healthy_profile_proxy',
    section: 'suggested',
    status: 'implemented',
    category: { ru: 'Питание', en: 'Nutrition profile' },
    label: { ru: 'Proxy здорового профиля', en: 'Healthy profile proxy' },
    shortDescription: { ru: 'Сочетание овощей, фруктов, молочных и низкого meat-сигнала.', en: 'A combination of vegetables, fruits, dairy and a low meat signal.' },
    whyItMatters: { ru: 'Полезно для мягкой content- и category-персонализации.', en: 'Useful for soft content and category personalization.' },
    calculation: { ru: 'Можно строить на bought_vegetables, bought_fruits, bought_milk и vegetarian_profile.', en: 'Can be built on bought_vegetables, bought_fruits, bought_milk and vegetarian_profile.' },
    sourceFields: ['purchase_items_mart.customer_id', 'purchase_items_mart.purchase_dt', 'products_mart.category_raw'],
    sourceTables: itemTables,
    lookbackDays: 90,
    lookbackWindow: sparkWindow(90),
    thresholdDescription: { ru: 'Это именно proxy, а не факт о реальном рационе.', en: 'This is a proxy, not a fact about the real diet.' },
    interpretationZero: { ru: 'Нет устойчивого healthy-like паттерна.', en: 'No stable healthy-like pattern.' },
    interpretationOne: { ru: 'Есть healthy-like паттерн в покупках.', en: 'There is a healthy-like purchasing pattern.' },
    currentProxyFeatureKeys: ['bought_vegetables_last_30d', 'bought_fruits_last_30d', 'bought_milk_last_30d', 'vegetarian_profile'],
  }),
];

const explicitMap = new Map(explicitCurrentDefinitions.map((item) => [item.key, item]));

export function getFeatureDefinition(key: string): FeatureDefinition | null {
  return explicitMap.get(key) ?? buildPatternDefinition(key);
}

export function localizeFeatureDefinition(definition: FeatureDefinition, language: Lang): LocalizedFeatureDefinition {
  return {
    key: definition.key,
    section: definition.section,
    status: definition.status,
    category: definition.category[language],
    label: definition.label[language],
    shortDescription: definition.shortDescription[language],
    whyItMatters: definition.whyItMatters[language],
    calculation: definition.calculation[language],
    sourceFields: definition.sourceFields,
    sourceTables: definition.sourceTables,
    lookbackDays: definition.lookbackDays,
    lookbackWindow: definition.lookbackWindow[language],
    thresholdDescription: definition.thresholdDescription[language],
    interpretationZero: definition.interpretationZero[language],
    interpretationOne: definition.interpretationOne[language],
    caveats: definition.caveats?.[language],
    implementationNote: definition.implementationNote?.[language],
    currentProxyFeatureKeys: definition.currentProxyFeatureKeys,
  };
}

export function getLocalizedFeatureDefinition(key: string, language: Lang): LocalizedFeatureDefinition | null {
  const definition = getFeatureDefinition(key);
  return definition ? localizeFeatureDefinition(definition, language) : null;
}

export function getFeatureLabel(key: string, language: Lang): string {
  const definition = getFeatureDefinition(key);
  return definition ? definition.label[language] : key;
}

export const CURRENT_FEATURE_REGISTRY = explicitCurrentDefinitions;
export const SUGGESTED_FEATURE_REGISTRY = suggestedFeatureDefinitions;
